version: '2'
services:
  db:
    build: .
    volumes:
      # slim database dump
      - ${PWD}/cnx_slim_dump.2018-05-13.4.sql.gz:/docker-entrypoint-initdb.d/cnx_slim_dump.sql.gz
      - ./docs:/src/docs:z
      - ./cnxdb:/src/cnxdb:z
      - ./htmlcov:/src/htmlcov:z
      - ./.dockerfiles/initdb.d/:/docker-entrypoint-initdb.d/:z
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - DB_URL=postgresql://rhaptos@localhost/repository
      - DB_SUPER_URL=postgresql://postgres@localhost/repository
volumes:
  pg-data:
