version: '2'
services:
  db:
    build: .
    volumes:
      - ./docs:/src/docs:z
      - ./cnxdb:/src/cnxdb:z
      - ./htmlcov:/src/htmlcov:z
      - ./.dockerfiles/initdb.d/:/docker-entrypoint-initdb.d/:z
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - DB_URL=postgresql://rhaptos@/repository
      - DB_SUPER_URL=postgresql://postgres@/repository
volumes:
  pg-data:
