version: '2'
services:
  db:
    build: .
    volumes:
      - ./docs:/src/docs:z
      - ./cnxdb:/src/cnxdb:z
      - ./htmlcov:/src/htmlcov:z
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - DB_USER=rhaptos
      - DB_NAME=repository
      - POSTGRES_DB=repository
      - DB_URL=postgresql://rhaptos@localhost/repository
      - DB_SUPER_URL=postgresql://postgres@localhost/repository
volumes:
  pg-data:
