-- ###
-- Copyright (c) 2018, Rice University
-- This software is subject to the provisions of the GNU Affero General
-- Public License version 3 (AGPLv3).
-- See LICENCE.txt for details.
-- ###

INSERT INTO public.languages VALUES ('vi', NULL);
INSERT INTO public.languages VALUES ('sh', NULL);
INSERT INTO public.languages VALUES ('sr-yu', NULL);
INSERT INTO public.languages VALUES ('el', NULL);
INSERT INTO public.languages VALUES ('mk', NULL);
INSERT INTO public.languages VALUES ('ts', NULL);
INSERT INTO public.languages VALUES ('hr', NULL);
INSERT INTO public.languages VALUES ('pl', NULL);
INSERT INTO public.languages VALUES ('uk', NULL);
INSERT INTO public.languages VALUES ('ja', NULL);
INSERT INTO public.languages VALUES ('th', NULL);
INSERT INTO public.languages VALUES ('ar', NULL);
INSERT INTO public.languages VALUES ('lv', NULL);
INSERT INTO public.languages VALUES ('ca', NULL);
INSERT INTO public.languages VALUES ('sr', NULL);
INSERT INTO public.languages VALUES ('bn', NULL);
INSERT INTO public.languages VALUES ('bn-bd', NULL);
INSERT INTO public.languages VALUES ('ko', NULL);
INSERT INTO public.languages VALUES ('et', NULL);
INSERT INTO public.languages VALUES ('ko-kr', NULL);
INSERT INTO public.languages VALUES ('af', NULL);
INSERT INTO public.languages VALUES ('eo', NULL);
INSERT INTO public.languages VALUES ('fi', 'finnish');
INSERT INTO public.languages VALUES ('en-tt', 'english');
INSERT INTO public.languages VALUES ('en-ca', 'english');
INSERT INTO public.languages VALUES ('da', 'danish');
INSERT INTO public.languages VALUES ('zh-hk', 'chinese');
INSERT INTO public.languages VALUES ('en-us', 'english');
INSERT INTO public.languages VALUES ('fr-fr', 'french');
INSERT INTO public.languages VALUES ('sv', 'swedish');
INSERT INTO public.languages VALUES ('es-cu', 'spanish');
INSERT INTO public.languages VALUES ('fr', 'french');
INSERT INTO public.languages VALUES ('it-it', 'italian');
INSERT INTO public.languages VALUES ('nl', 'dutch');
INSERT INTO public.languages VALUES ('pt-pt', 'portuguese');
INSERT INTO public.languages VALUES ('zh', 'chinese');
INSERT INTO public.languages VALUES ('en-gb', 'english');
INSERT INTO public.languages VALUES ('ro', 'romanian');
INSERT INTO public.languages VALUES ('de', 'german');
INSERT INTO public.languages VALUES ('es', 'spanish');
INSERT INTO public.languages VALUES ('es-es', 'spanish');
INSERT INTO public.languages VALUES ('ru', 'russian');
INSERT INTO public.languages VALUES ('tr', 'turkish');
INSERT INTO public.languages VALUES ('en-ng', 'english');
INSERT INTO public.languages VALUES ('es-mx', 'spanish');
INSERT INTO public.languages VALUES ('hu', 'hungarian');
INSERT INTO public.languages VALUES ('es-pe', 'spanish');
INSERT INTO public.languages VALUES ('de-de', 'german');
INSERT INTO public.languages VALUES ('es-ar', 'spanish');
INSERT INTO public.languages VALUES ('en-as', 'english');
INSERT INTO public.languages VALUES ('pt-br', 'portuguese');
INSERT INTO public.languages VALUES ('hu-hu', 'hungarian');
INSERT INTO public.languages VALUES ('zh-cn', 'chinese');
INSERT INTO public.languages VALUES ('it', 'italian');
INSERT INTO public.languages VALUES ('es-ve', 'spanish');
INSERT INTO public.languages VALUES ('nl-nl', 'dutch');
INSERT INTO public.languages VALUES ('en', 'english');
INSERT INTO public.languages VALUES ('es-pr', 'spanish');
INSERT INTO public.languages VALUES ('es-co', 'spanish');
INSERT INTO public.languages VALUES ('en-za', 'english');
INSERT INTO public.languages VALUES ('da-dk', 'danish');
INSERT INTO public.languages VALUES ('es-cl', 'spanish');
INSERT INTO public.languages VALUES ('pt', 'portuguese');
